# Generated by Django 4.2.3 on 2023-07-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0003_alter_song_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="playlist_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="playlist.playlist",
            ),
        ),
        migrations.DeleteModel(name="Song_list",),
    ]
